#!/bin/bash

set -e

HOST=$(hostname)
OUTDIR=captures

i=2
while [ -e "$OUTDIR/$HOST.dmidecode" ]; do
	HOST="$HOST-$i"
	let i=i+1
done

dmidecode > "$OUTDIR/$HOST.dmidecode"
dmesg > "$OUTDIR/$HOST.dmesg"
lspci > "$OUTDIR/$HOST.lspci"
lspci -vvv -xxxx > "$OUTDIR/$HOST.xlspci"
lspci -t > "$OUTDIR/$HOST.tree"
cat /proc/bus/pci/devices > "$OUTDIR/$HOST.proc"
cat /proc/iomem > "$OUTDIR/$HOST.iomem"
